### ISSUE TITLE
tex2xml interpreter change to sh doesn't work outside of docker

### ISSUE THREAD

**Issue by hfmark** [WeAreSeismica/tex2jats#4]
To run the tex2xml conversion script on my local machine, I have to change the interpreter from sh to bash. The issue seems to be in line 52 - VAR doesn't get expanded into {1..20} in sh, so the regex gets an argument with an unescaped brace and is not happy about that. It looks from the commit history like the interpreter was changed to sh for compatibility with docker. Is there a way around this, either making bash work for docker or putting in a loop that works for sh outside of docker?

**Comment by abhineetgupta** [comment]
PR - https://github.com/WeAreSeismica/tex2jats/pull/5

**Comment by hfmark** [comment]
Issue resolved with `seq`
