### ISSUE TITLE
png suffix

### ISSUE THREAD

**Issue by hfmark** [WeAreSeismica/tex2jats#6]
The scripts are set up right now to append ".png" to figure references, which is fine even if it has to be corrected when authors provide pdfs, but it also seems to be appending ".png" to the end of whatever is in `xlink:href` for latex `\url{}`s. This is probably not all that difficult to fix but for now it's faster for me just to correct the xml galleys by hand than actually deal with it

**Comment by thearagon** [comment]
Haha that's funny for the png at the end of the url... I guess I should check previously published urls!
Fixed with commit "fix png suffix"
